### PR TITLE
Paintroid 721 : Add PR number to the app name

### PR DESCRIPTION
**Pull request by vishad-tyagi**
Ticket : Paintroid-721 
https://catrobat.atlassian.net/browse/PAINTROID-721

Description
Add the PR number to the app name, so we can see which version is installed instantly.
Also change the app identifier so that we are able to install multiple apps from different PRs at the same time.

## New Features and Enhancements
- New Features and Enhancements
## Refactorings and Bug Fixes
- Refactorings and Bug Fixes

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by msesko** [comment]
Wait, didnt we already implement this once?

**Comment by vishad-tyagi** [comment]
@msesko No, that was for adding a PR number to the generated apk file.
This one adds PR number to the app name and identifier so a reviewer can test multiple PRs in a simulator at the same time.

**Comment by msesko** [comment]
> @msesko No, that was for adding a PR number to the generated apk file. This one adds PR number to the app name and identifier so a reviewer can test multiple PRs in a simulator at the same time.

ah ok makes sense. code looks good and it seems to work. approved

**Review by msesko — APPROVED** [review]

**Review by juliajulie95 — APPROVED** [review]
Thank you!

**Pull request merged**
