### PR TITLE
PAINTROID-701: Addition of Tooltips

### PR DESCRIPTION
**Pull request by bhav-khurana**
## Ticket
[PAINTROID 701](https://jira.catrob.at/browse/PAINTROID-701)

## New Features and Enhancements
Adds tooltips at places like `Load image` and the `New image` buttons and the like to enhance user experience and let the user know the functionality of each of the buttons clearly.

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by bhav-khurana** [comment]
@bakicelebi The requested changes have been addressed. Can you please have a look?

**Comment by bhav-khurana** [comment]
@bakicelebi @juliajulie95 Is there any other change required?

**Review by bakicelebi — APPROVED** [review]
👍🏻  Looks good.

**Comment by bhav-khurana** [comment]
@juliajulie95
Any suggestions from your side?

**Comment by juliajulie95** [comment]
Thank you!

**Pull request merged**
