### PR TITLE
PAINTROID-703: Fix bottom overflow

### PR DESCRIPTION
**Pull request by bhav-khurana**
## Ticket
[PAINTROID 703](https://jira.catrob.at/browse/PAINTROID-702)

## Refactorings and Bug Fixes
Fixed the bottom overflow in the tools list in the drawing page by adjusting the aspect ratio and making the size of the bottom sheet dynamic wrt the screen size.

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by bhav-khurana** [comment]
@juliajulie95 @bakicelebi can you please have a look at the changes?

**Comment by bhav-khurana** [comment]
@bakicelebi
Can you please review the changes?

**Comment by juliajulie95** [comment]
Please resolve your conflicts :)

**Comment by Lenkomotive** [comment]
@bhav-khurana Are you working on this ticket?

**Comment by bhav-khurana** [comment]
Yes I'll be resolving the conflicts.. will make a commit in a day or two

**Review by Lenkomotive — CHANGES_REQUESTED** [review]
Hey! Good work! Looks like you located the issue correctly. There is one thing that should be resolved tho:

Portrait mode looks good, but the landscape mode needs some adjustment. 
Please try to make it dynamic based on orientation, consider increasing the crossAxisCount in landscape mode to make use of the screen width (test on tablets and other devices). 
Also you might need to adjust the spacing between the icons and don't forget to write good tests ;)

Cheers :)
image

**Comment by bhav-khurana** [comment]
@Lenkomotive I have made the `crossAxisCount` dynamic and checked it for portrait as well as landscape mode

**Comment by Lenkomotive** [comment]
@bhav-khurana please stick to GridView or at least make sure all icons are aligned. You can make use of the MediaQuery to check the orientation. Maybe go for 4 tool columns in portrait, and 8 in landscape mode. But make sure to test it well on different devices. Cheers :)

**Comment by bhav-khurana** [comment]
> @bhav-khurana please stick to GridView or at least make sure all icons are aligned. You can make use of the MediaQuery to check the orientation. Maybe go for 4 tool columns in portrait, and 8 in landscape mode. But make sure to test it well on different devices. Cheers :)

Actually instead of hardcoding the cross axis count for portrait and landscape, I was thinking of using the `Wrap` widget as it would automatically adjust it based on size.. 
I will look into the alignment of the icons though and make sure they fit well :)

**Comment by Lenkomotive** [comment]
@bhav-khurana  
Hey! I have checked out your changes. It looks better now, but the actual issue is still not resolved. 

- `Wrap` will move the icon to the next line, if there is not enough space available (see example in ss with ip13mini and ip15max) => what we actually want is to have a fixed order which is responsive based on orientation. (4 in portrait, 8 in landscape)
- `SingleChildScrollView` might not be the right choice here, since we want all the tools to be displayed without the need to scroll.

Please try to find a responsive solution. Since there are some constant values in the current implementation, this can be tricky I understand, but they are the actual evil that are keeping us from having a good working `toolBottomSheet`.

I hope you can work with this. Cheers! ;)

image

**Review by Lenkomotive — DISMISSED** [review]
see comment :)

**Comment by bhav-khurana** [comment]
Okay I got the problem now! Will try to resolve it as expected.. thank you :)

**Review by msesko — APPROVED** [review]
Hi @bhav-khurana , looks really nice. I tested this on iphone too, because there was overflow in portrait on there before. now it looks really good in portrait and landscape. approved.

**Review by juliajulie95 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
