### PR TITLE
PAINTROID-512 allo package imports only

### PR DESCRIPTION
**Pull request by davidmoling**
Ticket: https://jira.catrob.at/browse/PAINTROID-512

### CODE REVIEW

**Comment by juliajulie95** [comment]
Code looks fine, github action currently fails because of protoc setup, which is not related to this PR though

**Review by juliajulie95 — APPROVED** [review]

**Comment by juliajulie95** [comment]
After a re-run action completed succesfully

**Comment by CodeChamp-SS** [comment]
The changes LGTM, please resolve the merge conflicts

**Review by CodeChamp-SS — APPROVED** [review]
LGTM

**Pull request merged**
